mainSections: post
rssFullContent: true
favicon: https://cdn.sunyz.net/favicons/favicon.ico

footer:
  since: 2023
  customText:

dateFormat:
  published: Jan 02, 2006
  lastUpdated: Jan 02, 2006 15:04 MST

sidebar:
  emoji: ğŸ
  subtitle: ä¸‹ä¸€æ¬¡ç›¸é‡å¯èƒ½åœ¨ä»»ä½•åœ°æ–¹ï¼Œä½†æˆ‘ä»¬å§‹ç»ˆç¿çƒ‚å¦‚æ˜Ÿæµ·ã€‚
  avatar:
    enabled: true
    local: false
    src: https://cdn.sunyz.net/avatar@512x512.png

article:
  math: true
  readingTime: true
  license:
    enabled: true
    default: Licensed under CC BY-NC-SA 4.0

colorScheme:
  toggle: true
  default: auto

comments:
  enabled: true
  provider: disqus

imageProcessing:
  cover:
    enabled: true
  content:
    enabled: true